### PR TITLE
Provide Spring Boot Sample app

### PR DESCRIPTION
**Pull request by KarstenSchnitter**
This PR provides a new sample application using Spring Boot.
It is secured with basic authentication.
The app can be used as a JWT generator for dynamic log levels.

### CODE REVIEW

**Comment by juergen-walter** [comment]
Do not merge, I get an error when running mvn install.

`cf-java-logging-support/sample-spring-boot$ mvn install -X`
...
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project sample-app-spring-boot: Fatal error compiling: invalid flag: --release -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project sample-app-spring-boot: Fatal error compiling
```
...
`Caused by: java.lang.IllegalArgumentException: invalid flag: --release`

**Comment by KarstenSchnitter** [comment]
@juergen-walter: I used Maven version 3.6.3. What is your maven version?

**Comment by juergen-walter** [comment]
> @juergen-walter: I used Maven version 3.6.3. What is your maven version?

$ mvn --version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_282, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-65-generic", arch: "amd64", family: "unix"

**Comment by juergen-walter** [comment]
will try it with updated maven

**Comment by juergen-walter** [comment]
Could verify that it works with Maven 3.6.0

**Comment by juergen-walter** [comment]
Tested everything locally, worked as expected/documented.

I created a PR with minors to the sample-spring-boot branch
https://github.com/SAP/cf-java-logging-support/pull/95

**Comment by juergen-walter** [comment]
Without deeply looking into it, the continuous-integration check failures look like to be fixed in the test system itself:
https://stackoverflow.com/questions/52279372/mvn-clean-install-error-error-could-not-create-the-java-virtual-machine-error

**Comment by juergen-walter** [comment]
I think the "Add debug to travis maven execution" commit has to be reverted to make the CI tests pass

**Comment by juergen-walter** [comment]
My PR has still a small improvement https://github.com/SAP/cf-java-logging-support/pull/94/files

Marked the relevant changes with strike-through and bold.

sample-spring-boot/README.md 
## Getting Started

This sample application is contained in the Maven module sample-spring-boot.
~~It can be built with a simple `mvn install`.~~
A minimal CF application manifest is provided in [manifest.yml.](manifest.yml)
**To avoid naming conflicts, the name of the app should be changed in the manifest before building it.
The app can be built with a simple `mvn install`** (requires Apache Maven 3.6.3).
This allows to deploy the newly built app with `cf push`, provided a login to a CF instance.

**Review by juergen-walter — APPROVED** [review]
Added a small improvement idea, feel free to include or not. Approved.

**Pull request merged**
