### PR TITLE
Added Closeable to RequestRecord

### PR DESCRIPTION
**Pull request by torax242**
Added the Closeable interface to RequestRecord to point out to anyone that manually uses this class that it needs to be closed in order to avoid memory leaks.

### CODE REVIEW

**Comment by C-Otto** [comment]
Is there a reason why you decided against `AutoCloseable`?

**Comment by torax242** [comment]
Yes. I've looked at the Maven pom and found no restriction to a specific Java version. Therefore I couldn't assume a Java language version >= 1.7 and that is the version where `AutoCloseable` was introduced. Java 1.5 on the other hand is so old that I took that for granted.

**Comment by C-Otto** [comment]
That makes sense. @altenhof maybe you want to specify the Java version to avoid issues like this?

**Comment by altenhof** [comment]
@C-Otto, specify it where?

**Comment by C-Otto** [comment]
https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html

**Pull request merged**
